http:
  routers:
    my-router:
      rule: host(`api.massive-dynamic.com`)
      service: service-default
      entryPoints:
        - web
      middlewares:
        - TraefikRegionalPlugin
    my-ja-router:
      rule: host(`api.ja.massive-dynamic.com`)
      service: service-ja
      entryPoints:
        - web
    my-na-router:
      rule: host(`api.na.massive-dynamic.com`)
      service: service-na
      entryPoints:
        - web

  services:
    service-ja:
      loadBalancer:
        servers:
          - url:  http://whoami-ja:80
    service-default:
      loadBalancer:
        servers:
          - url: http://whoami-default:80
    service-na:
      loadBalancer:
        servers:
          - url: http://whoami-na:80

  middlewares:
    TraefikRegionalPlugin:
      plugin:
        dev:
          GlobalHostUrls:
            - "api.massive-dynamic.com"
          MatchPaths:
            - regex: ^\/api\/projects\/(([0-9A-Fa-f]{8}[-]){2,}([0-9A-Fa-f]{4}[-]){3}[0-9A-Fa-f]{12})$
              type: "PATH"
              index: 0
            - regex: ^\/project$
              type: "JWT"
              methods:
                - "POST"
          DestinationHosts:
            - host: "api.ja.massive-dynamic.com"
              value: 1
              isCurrent: false
            - host: "api.na.massive-dynamic.com"
              value: 2
              isCurrent: false
          IsLittleEndian: true
          DefaultScheme: http
          Log: Debug
          RoutingMethod: Redirect
