http:
  routers:
    my-router:
      rule: host(`whoami.localhost`)
      service: service-foo
      entryPoints:
        - web
      middlewares:
        - TraefikRegionalPlugin
    my-ja-router:
      rule: host(`whoami.ja.localhost`)
      service: service-foo
      entryPoints:
        - web
    my-na-router:
      rule: host(`whoami.na.localhost`)
      service: service-foo
      entryPoints:
        - web

  services:
    service-foo:
      loadBalancer:
        servers:
          - url: http://whoami:80

  middlewares:
    TraefikRegionalPlugin:
      plugin:
        dev:
          GlobalHostUrls:
            - "whoami.localhost"
          MatchPaths:
            - regex: ^\/project\/(([0-9A-Fa-f]{8}[-]){2,}([0-9A-Fa-f]{4}[-]){3}[0-9A-Fa-f]{12})$
              type: "PATH"
              index: 0
            - regex: ^\/project$
              type: "JWT"
              methods:
                - "POST"
          DestinationHosts:
            - host: "whoami.ja.localhost"
              value: 1
            - host: "whoami.na.localhost"
              value: 2
          IsLittleEndian: true
          DefaultScheme: http
          Log: Information
          Airbrake:
            ProjectId: 42
            ProjectKey: "test"
            Environment: "Local"
