http:
  routers:
    my-router:
      rule: host(`whoami.localhost`)
      service: service-default
      entryPoints:
        - web
      middlewares:
        - TraefikRegionalPlugin
    my-ja-router:
      rule: host(`whoami.ja.localhost`)
      service: service-ja
      entryPoints:
        - web
    my-na-router:
      rule: host(`whoami.na.localhost`)
      service: service-na
      entryPoints:
        - web

  services:
    service-ja:
      loadBalancer:
        servers:
          - url:  http://whoami-ja:80
    service-default:
      loadBalancer:
        servers:
          - url: http://whoami-default:80
    service-na:
      loadBalancer:
        servers:
          - url: http://whoami-na:80

  middlewares:
    TraefikRegionalPlugin:
      plugin:
        dev:
          GlobalHostUrls:
            - "whoami.localhost"
          MatchPaths:
            - regex: ^\/api\/projects\/(([0-9A-Fa-f]{8}[-]){2,}([0-9A-Fa-f]{4}[-]){3}[0-9A-Fa-f]{12})$
              type: "PATH"
              index: 0
            - regex: ^\/project$
              type: "JWT"
              methods:
                - "POST"
          DestinationHosts:
            - host: "projects-service-api.priv.eu.sandbox.finalcad.cloud"
              value: 1
            - host: "whoami.na.localhost"
              value: 2
          IsLittleEndian: true
          DefaultScheme: http
          Log: Information
