version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik_finalcad"
    command:
      - "--configFile=/config/static-config.yaml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./static-config.yaml:/config/static-config.yaml"
      - "./dynamics:/config/dyns/"
      - "../.:/plugins/go/src/github.com/finalcad/TraefikRegionalPlugin/"

  whoami-ja:
    image: "traefik/whoami"
    container_name: "whoami-ja"
    ports:
      - "8001:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=japan-router"
  whoami-na:
    image: "traefik/whoami"
    container_name: "whoami-na"
    ports:
      - "8002:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=north-america-router"
  whoami-default:
    image: "traefik/whoami"
    container_name: "whoami-default"
    ports:
      - "8003:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=default-router"

