name: traefik-regional-plugin

services:

  traefik:
    image: "traefik:v2.11"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./files/traefik/etc:/etc/traefik"
      - "..:/plugins-local/src/github.com/FinalCAD/TraefikRegionalPlugin"

  whoami-ja:
    image: "traefik/whoami"
    ports:
      - "8001:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=japan-router"
  whoami-na:
    image: "traefik/whoami"
    ports:
      - "8002:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=north-america-router"
  whoami-default:
    image: "traefik/whoami"
    ports:
      - "8003:80"
    labels:
      - "traefik.enable=true"
    environment:
      - "WHOAMI_NAME=default-router"

