pilot:
  token: token 12
log:
  level: INFO
api:
  insecure: true
providers:
  docker:
    exposedbydefault: false
  file:
    directory: /config/dyns
    watch: true
entrypoints:
  web:
    address: ":80"
accesslog: {}
experimental:
  devPlugin:
    goPath: /plugins/go
    moduleName: github.com/finalcad/TraefikRegionalPlugin
